# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fooider' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fooider
  pod "Koloda"
  pod 'AFNetworking', '~> 2.5'
  pod 'BDBOAuth1Manager'

  target 'FooiderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FooiderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
